import {test} from 'node:test';import assert from 'node:assert/strict';import {recheckFindings} from '../src/check-evidence.js';import type {IntakeLinked} from '../src/intake.js';
const result:IntakeLinked={schema_version:'intake.v1',summary:'SYNTHETIC',category:'support',urgency:'unknown',fields:[{name:'dose_1',value:'10 mg',quote:'2) SYN-B 10 mg HS',verified:false,evidence:[]}],sourceLines:[{quote:'1) SYN-A 5 mg BD',confidence:null},{quote:'2) SYN-B 10 mg HS',confidence:null}],missing:[],reviewReasons:[],inputHash:'fixture',transcript:null,tokens:0,usd:0,useCase:'prescription',cacheHit:true};
const finding={field:'dose_1',reading:'10 mg',status:'text_agrees',reason:'Old cached agreement',score:.999};
test('cached checker results cannot preserve cross-row false agreement; raw scores unchanged',()=>{const out=recheckFindings(result,[finding]);assert.equal(out[0].status,'needs_check');assert.equal(out[0].score,.999);assert.equal(finding.status,'text_agrees');});
test('cached checker agreement for changed or duplicate field is rejected',()=>{assert.equal(recheckFindings(result,[{...finding,reading:'5 mg'}])[0].status,'needs_check');assert.equal(recheckFindings({...result,fields:[result.fields[0],result.fields[0]]},[finding])[0].status,'needs_check');});
test('supported saved text agreement is retained, never promoted from needs_check',()=>{const r={...result,fields:[{...result.fields[0],name:'dose_2'}]};const f={...finding,field:'dose_2'};assert.equal(recheckFindings(r,[f])[0].status,'text_agrees');assert.equal(recheckFindings(r,[{...f,status:'needs_check'}])[0].status,'needs_check');});

test('field-written quote alone is not independent source evidence',()=>{const r={...result,sourceLines:undefined,fields:[{...result.fields[0],name:'dose_2'}]};assert.equal(recheckFindings(r,[{...finding,field:'dose_2'}])[0].status,'needs_check');});
test('revalidation preserves duplicate source lines and refuses ambiguous evidence',()=>{const r={...result,fields:[{...result.fields[0],name:'dose_2'}],sourceLines:[result.sourceLines![1],result.sourceLines![1]]};assert.equal(recheckFindings(r,[{...finding,field:'dose_2'}])[0].status,'needs_check');});
