import{test}from'node:test';import assert from'node:assert/strict';
import{intakeSchema,linkIntake}from'../src/intake.js';import{intake,intakeKey}from'../server/intake.js';import type{Input}from'../server/extraction.js';import type{Store,Entry,Ledger}from'../server/store.js';
const input:Input={text:'Invoice #F42\nAmount: 200 USD\nDue: 2026-10-01',file:null};
class MemoryStore implements Store{entries=new Map<string,Entry>();calls=0;async lookup(key:string){return this.entries.get(key)??null;}async reserve(key:string){this.calls++;this.entries.set(key,{status:'pending'});}async finish(key:string,e:Entry){this.entries.set(key,e);}async fail(key:string,e:string){this.entries.set(key,{status:'failed',error:e});}async ledger():Promise<Ledger>{return{tokens:0,usd:0,halted:false,lastCall:0};}}
const answer={schema_version:'intake.v1',summary:'Invoice due.',category:'payment',urgency:'soon',fields:[{name:'amount',value:'200 USD',quote:'Amount: 200 USD'}],missing:['payer']};
test('one multimodal-shaped structured call; cache is reused without repeat',async()=>{const store=new MemoryStore();let calls=0;const transport=(async(_url:string,options:RequestInit)=>{calls++;const payload=JSON.parse(String(options.body));assert.equal(payload.messages.length,2);assert.equal(payload.response_format.json_schema.name,'intake_v1');return new Response(JSON.stringify({choices:[{message:{content:JSON.stringify(answer)}}],usage:{prompt_tokens:100,completion_tokens:50}}),{status:200});}) as typeof fetch;const cfg={key:'test',freeConfirmed:true,tokenCap:2_000_000,creditCap:2};const first=await intake(input,store,cfg,transport);assert.equal(first.category,'payment');assert.equal(first.fields[0].verified,true);assert.ok(first.reviewReasons.some(x=>x.includes('category')));assert.equal(calls,1);assert.equal((await intake(input,store,cfg,transport)).cacheHit,true);assert.equal(calls,1);assert.equal(store.calls,1);assert.ok(await store.lookup(intakeKey(input)));});
test('ambiguous source quote cannot be called verified',()=>{const x=intakeSchema.parse(answer);const linked=linkIntake(x,undefined,'Amount: 200 USD\nAmount: 200 USD');assert.equal(linked.fields[0].verified,false);});
test('audio transcribes then classifies in two separate cached calls',async()=>{const store=new MemoryStore();let calls=0;const seen:unknown[]=[];const transport=(async(_url:string,options:RequestInit)=>{calls++;const payload=JSON.parse(String(options.body));seen.push(payload);const content=calls===1?{text:'Amount: 200 USD'}:{...answer,fields:[{name:'amount',value:'200 USD',quote:'Amount: 200 USD'}]};return new Response(JSON.stringify({choices:[{message:{content:JSON.stringify(content)}}],usage:{prompt_tokens:100,completion_tokens:50}}),{status:200});}) as typeof fetch;const audio:Input={text:'',file:{name:'fictional.ogg',mime:'audio/ogg',base64:'YWJj'}};const cfg={key:'test',freeConfirmed:true,tokenCap:4_000_000,creditCap:4};const r=await intake(audio,store,cfg,transport);assert.equal(calls,2);assert.equal(r.transcript,'Amount: 200 USD');assert.equal(r.fields[0].verified,true);assert.equal(r.tokens,300);assert.equal(r.usd,.00065);assert.equal((await intake(audio,store,cfg,transport)).cacheHit,true);assert.equal(calls,2);assert.equal(store.calls,2);assert.match(JSON.stringify(seen[0]),/intake_transcript_v1/);assert.doesNotMatch(JSON.stringify(seen[1]),/data:audio/);});
test('audio failure halts at transcription and never classifies or retries',async()=>{const store=new MemoryStore();let calls=0;const transport=(async()=>{calls++;return new Response('bad',{status:500});}) as typeof fetch;const audio:Input={text:'',file:{name:'fictional.ogg',mime:'audio/ogg',base64:'YWJj'}};const cfg={key:'test',freeConfirmed:true,tokenCap:4_000_000,creditCap:4};await assert.rejects(intake(audio,store,cfg,transport),/TRANSCRIPTION_HTTP_500/);await assert.rejects(intake(audio,store,cfg,transport),/TRANSCRIPTION_HTTP_500/);assert.equal(calls,1);assert.equal(store.calls,1);});
