import{test}from'node:test';import assert from'node:assert/strict';
import{intakeSchema,linkIntake}from'../src/intake.js';import{intake,intakeKey}from'../server/intake.js';import type{Input}from'../server/extraction.js';import type{Store,Entry,Ledger}from'../server/store.js';
const input:Input={text:'Invoice #F42\nAmount: 200 USD\nDue: 2026-10-01',file:null};
class MemoryStore implements Store{entries=new Map<string,Entry>();calls=0;async lookup(key:string){return this.entries.get(key)??null;}async reserve(key:string){this.calls++;this.entries.set(key,{status:'pending'});}async finish(key:string,e:Entry){this.entries.set(key,e);}async fail(key:string,e:string){this.entries.set(key,{status:'failed',error:e});}async ledger():Promise<Ledger>{return{tokens:0,usd:0,halted:false,lastCall:0};}}
const answer={schema_version:'intake.v1',summary:'Invoice due.',category:'payment',urgency:'soon',fields:[{name:'amount',value:'200 USD',quote:'Amount: 200 USD'}],missing:['payer']};
test('one multimodal-shaped structured call; cache is reused without repeat',async()=>{const store=new MemoryStore();let calls=0;const transport=(async(_url:string,options:RequestInit)=>{calls++;const payload=JSON.parse(String(options.body));assert.equal(payload.messages.length,2);assert.equal(payload.response_format.json_schema.name,'intake_v1');return new Response(JSON.stringify({choices:[{message:{content:JSON.stringify(answer)}}],usage:{prompt_tokens:100,completion_tokens:50}}),{status:200});}) as typeof fetch;const cfg={key:'test',freeConfirmed:true,tokenCap:2_000_000,creditCap:2};const first=await intake(input,store,cfg,transport);assert.equal(first.category,'payment');assert.equal(first.useCase,'prescription');assert.equal(first.fields[0].verified,true);assert.ok(first.reviewReasons.some(x=>x.includes('category')));assert.equal(calls,1);assert.equal((await intake(input,store,cfg,transport)).cacheHit,true);assert.equal(calls,1);assert.equal(store.calls,1);assert.ok(await store.lookup(intakeKey(input)));});
test('ambiguous source quote cannot be called verified',()=>{const x=intakeSchema.parse(answer);const linked=linkIntake(x,undefined,'Amount: 200 USD\nAmount: 200 USD');assert.equal(linked.fields[0].verified,false);});
test('audio transcribes then classifies in two separate cached calls',async()=>{const store=new MemoryStore();let calls=0;const seen:unknown[]=[];const transport=(async(_url:string,options:RequestInit)=>{calls++;const payload=JSON.parse(String(options.body));seen.push(payload);const content=calls===1?{text:'Amount: 200 USD'}:{...answer,fields:[{name:'amount',value:'200 USD',quote:'Amount: 200 USD'}]};return new Response(JSON.stringify({choices:[{message:{content:JSON.stringify(content)}}],usage:{prompt_tokens:100,completion_tokens:50}}),{status:200});}) as typeof fetch;const audio:Input={text:'',file:{name:'fictional.ogg',mime:'audio/ogg',base64:'YWJj'}};const cfg={key:'test',freeConfirmed:true,tokenCap:4_000_000,creditCap:4};const r=await intake(audio,store,cfg,transport);assert.equal(calls,2);assert.equal(r.transcript,'Amount: 200 USD');assert.equal(r.fields[0].verified,true);assert.equal(r.tokens,300);assert.equal(r.usd,.00065);assert.equal((await intake(audio,store,cfg,transport)).cacheHit,true);assert.equal(calls,2);assert.equal(store.calls,2);assert.match(JSON.stringify(seen[0]),/intake_transcript_v1/);assert.doesNotMatch(JSON.stringify(seen[1]),/data:audio/);});
test('audio failure halts at transcription and never classifies or retries',async()=>{const store=new MemoryStore();let calls=0;const transport=(async()=>{calls++;return new Response('bad',{status:500});}) as typeof fetch;const audio:Input={text:'',file:{name:'fictional.ogg',mime:'audio/ogg',base64:'YWJj'}};const cfg={key:'test',freeConfirmed:true,tokenCap:4_000_000,creditCap:4};await assert.rejects(intake(audio,store,cfg,transport),/TRANSCRIPTION_HTTP_500/);await assert.rejects(intake(audio,store,cfg,transport),/TRANSCRIPTION_HTTP_500/);assert.equal(calls,1);assert.equal(store.calls,1);});

test('prescription prompt forbids guessing unreadable medicine names and creating reminders',async()=>{const store=new MemoryStore();let prompt='';const transport=(async(_url:string,options:RequestInit)=>{const payload=JSON.parse(String(options.body));prompt=payload.messages[0].content;return new Response(JSON.stringify({choices:[{message:{content:JSON.stringify({...answer,fields:[],missing:['medicine_1 illegible']})}}],usage:{prompt_tokens:10,completion_tokens:10}}),{status:200});}) as typeof fetch;const r=await intake({text:'fictional scribble',file:null},store,{key:'test',freeConfirmed:true,tokenCap:2_000_000,creditCap:2},transport);assert.deepEqual(r.fields,[]);assert.equal(r.missing.length,4);assert.match(r.missing[0],/Medicine name 1/);assert.match(prompt,/1-0-1/);assert.match(prompt,/Never repair 3 X to 3 d/);assert.match(prompt,/do NOT guess/);assert.match(prompt,/Do not create reminders/);});

test('exact excerpt in one OCR line links without guessing letters; whitespace only is normalized',()=>{const point=(x:number,y:number)=>({x,y});const raw=[{name:'ocr',result:{width:100,height:100,sections:[{lines:[{text:'1) FictionalName 5 mg  BD',average_confidence:.99,bounds:{top_left:point(0,0),top_right:point(80,0),bottom_left:point(0,10),bottom_right:point(80,10)}}]}]}}];
 const r=linkIntake(intakeSchema.parse({...answer,fields:[{name:'frequency_1',value:'BD',quote:'FictionalName 5 mg BD'}]}),raw,'');assert.equal(r.fields[0].verified,true);assert.equal(r.sourceLines?.length,1);
 const mismatch=linkIntake(intakeSchema.parse({...answer,fields:[{name:'frequency_1',value:'TDS',quote:'1) FictionalName 5 mg BD'}]}),raw,'');assert.equal(mismatch.fields[0].verified,false);
});
test('saved provider metadata is relinked with zero provider calls and original usage',async()=>{const {savedIntake}=await import('../server/intake.js');const saved={...answer,...linkIntake(intakeSchema.parse(answer),undefined,''),inputHash:'x',transcript:null,tokens:150,usd:.002,cacheHit:false,useCase:'prescription' as const};const result=savedIntake({status:'ok',result:saved,raw:{choices:[{message:{content:JSON.stringify(answer)}}],usage:{prompt_tokens:100,completion_tokens:50}}},input);assert.equal(result.fields[0].verified,true);assert.equal(result.tokens,150);assert.equal(result.usd,.002);assert.equal(result.cacheHit,true);});
test('OCR full text survives missing and malformed boxes without invented confidence',async()=>{const {evidenceFrom}=await import('../src/ground.js');const r=evidenceFrom([{name:'ocr',result:{extracted_text:'THS\nMonitor',sections:[{lines:[{text:'THS',bounds:{bad:true}}]}]}}],'');assert.deepEqual(r,[{quote:'THS',confidence:null},{quote:'Monitor',confidence:null}]);});
test('one malformed OCR line does not discard other valid lines or duplicate full-text fallback',async()=>{const {evidenceFrom}=await import('../src/ground.js');const r=evidenceFrom([{name:'ocr',result:{width:100,height:100,extracted_text:'BD\nTHS',sections:[{lines:[{text:'BD',average_confidence:.9},{invalid:true}]}]}}],'');assert.deepEqual(r,[{quote:'BD',confidence:.9},{quote:'THS',confidence:null}]);});
test('future intake is deterministic and cannot treat procedures or unsupported shorthand as medicines',async()=>{const store=new MemoryStore();const transport=(async(_u,opts)=>{const p=JSON.parse(String(opts?.body));assert.equal(p.temperature,0);assert.match(p.messages[0].content,/clinical note rather than a medicine list/);assert.match(p.messages[0].content,/Never substitute TDS for THS/);return new Response(JSON.stringify({choices:[{message:{content:JSON.stringify({...answer,fields:[]})}}],usage:{prompt_tokens:20,completion_tokens:10}}));}) as typeof fetch;await intake({text:'Fictional procedure note',file:null},store,{key:'fixture',freeConfirmed:true,tokenCap:2_000_000,creditCap:2},transport);});
test('saved raw full OCR text is recovered without new reading or rewritten usage',async()=>{const {savedIntake}=await import('../server/intake.js');const saved={...answer,...linkIntake(intakeSchema.parse(answer),undefined,''),inputHash:'fixture',transcript:null,tokens:123,usd:.002,cacheHit:false,useCase:'prescription' as const};const r=savedIntake({status:'ok',result:saved,raw:{choices:[{message:{content:JSON.stringify({...answer,fields:[{name:'frequency_1',value:'THS',quote:'Foley monitor THS'}]})}}],usage:{prompt_tokens:100,completion_tokens:23},precontext:[{name:'ocr',result:{extracted_text:'Foley monitor THS'}}]}},{text:'',file:null});assert.equal(r.sourceLines?.[0].quote,'Foley monitor THS');assert.equal(r.sourceLines?.[0].confidence,null);assert.equal(r.tokens,123);assert.equal(r.usd,.002);assert.equal(r.cacheHit,true);});

test('literal field mapping rejects matching inside a larger dose or frequency token',()=>{
 const r=linkIntake(intakeSchema.parse({...answer,fields:[{name:'dose_1',value:'5 mg',quote:'1) Demo 15 mg BD'},{name:'frequency_1',value:'BD',quote:'1) Demo notBD'}]}),undefined,'1) Demo 15 mg BD\n1) Demo notBD');assert.equal(r.fields[0].verified,false);assert.equal(r.fields[1].verified,false);
});
test('numbered rows cannot exchange extracted dose fields',()=>{
 const r=linkIntake(intakeSchema.parse({...answer,fields:[{name:'dose_1',value:'10 mg',quote:'2) Demo 10 mg HS'},{name:'dose_2',value:'10 mg',quote:'2) Demo 10 mg HS'}]}),undefined,'1) Demo 5 mg BD\n2) Demo 10 mg HS');assert.equal(r.fields[0].verified,false);assert.equal(r.fields[1].verified,true);
});
import {linkIntake as _link} from '../src/intake.js';
import _test from 'node:test';import _assert from 'node:assert/strict';
_test('MOCK: single-word medicine-like reading links as one verified field, nothing invented',()=>{
 const r=_link({schema_version:'intake.v1',summary:'One word.',category:'support',urgency:'unknown',fields:[{name:'medicine_1',value:'Napa One',quote:'Napa One'}],missing:['dose_1','frequency_1','duration_1']},null,'Napa One');
 _assert.equal(r.fields.length,1);_assert.equal(r.fields[0].verified,true);_assert.ok(r.reviewReasons.some(x=>/human review/.test(x)));
});
import {scheduleReading as _sr} from '../src/prescription.js';
_test('scheduleReading: 1-0-1 is morning and night, not afternoon; shorthand is not expanded',()=>{
 _assert.match(_sr('1-0-1')!,/morning and night, not afternoon/);_assert.match(_sr('0-0-1')!,/night, not morning or afternoon/);_assert.equal(_sr('BD'),null);_assert.equal(_sr('TDS'),null);
});
import {readingIssue as _ri,prescriptionLabel as _pl} from '../src/prescription.js';
_test('quantity_N is a separate field and is not inferred',()=>{
 const f=(value:string)=>({name:'quantity_1',value,quote:value,evidence:[],verified:true});
 _assert.equal(_pl('quantity_1'),'Amount per dose 1');_assert.equal(_ri(f('1 tab')),null);_assert.equal(_ri(f('200 mg')) !== null,true);
});

const _q=(value:string,quote:string)=>({name:'quantity_1',value,quote,evidence:[],verified:true});
_test('quantity_N: explicit per-dose amount passes; absence is never derived from strength, timing, row number or Tab',()=>{
 _assert.equal(_ri(_q('1 tab','1) Tab Testmed 200mg 1 tab 1-0-1 5 d')),null);
 for(const [v,q] of [['1','1) Tab Testmed 200mg 1-0-1 5 d'],['1 tab','1) Tab Testmed 200mg 1-0-1 5 d'],['200','1) Tab Testmed 200mg 1-0-1 5 d'],['5','1) Tab Testmed 200mg 1-0-1 5 d'],['2','1) Tab Testmed 200mg 0-1-0 5 d']] as const)_assert.notEqual(_ri(_q(v,q)),null,`${v} in ${q}`);
});
import {linkIntake as _lk} from '../src/intake.js';
_test('MOCK: a row split across consecutive OCR lines links; a loose or ambiguous quote does not',()=>{
 const mk=(quote:string,value:string)=>({schema_version:'intake.v1' as const,summary:'x',category:'support' as const,urgency:'unknown' as const,fields:[{name:'medicine_1',value,quote}],missing:[]});
 const text='- T. Opox-CV\n200mg\n1-0-1\nunrelated';
 _assert.equal(_lk(mk('- T. Opox-CV 200mg 1-0-1','T. Opox-CV'),null,text).fields[0].verified,true);
 _assert.equal(_lk(mk('- T. Opox-CV 400mg 1-0-1','T. Opox-CV'),null,text).fields[0].verified,false);
 _assert.equal(_lk(mk('Opox-CV 200mg','Opox-CV'),null,text).fields[0].verified,false);
 _assert.equal(_lk(mk('- T. Opox-CV 200mg 1-0-1','Opox-CX'),null,text).fields[0].verified,false);
});
