import {test} from 'node:test';import assert from 'node:assert/strict';import {Readable} from 'node:stream';import {mkdtemp} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {checkJev} from '../server/jev-check.js';import {FileStore} from '../server/store.js';import {intakeKey} from '../server/intake.js';import type {IntakeLinked} from '../src/intake.js';
const input={text:'fictional prescription',file:null};
const linked:IntakeLinked={schema_version:'intake.v1',summary:'Fictional',category:'support',urgency:'unknown',fields:[{name:'medicine_1',value:'Samplemed',quote:'Rx Samplemed',evidence:[],verified:true}],missing:[],reviewReasons:[],inputHash:'abc',transcript:null,tokens:500,usd:0,cacheHit:false,useCase:'prescription'};
async function setup(){const dir=await mkdtemp(join(tmpdir(),'jev-check-'));const old=process.cwd();process.chdir(dir);process.env.TYPESAFE_JEV_API_KEY='fixture';process.env.JEV_PUBLIC_ENABLED='true';const s=new FileStore();await s.reserve(intakeKey(input),2_000_000,2);await s.finish(intakeKey(input),{status:'ok',result:linked},10,.001);return()=>{process.chdir(old);delete process.env.TYPESAFE_JEV_API_KEY;delete process.env.JEV_PUBLIC_ENABLED;};}
async function call(headers:Record<string,string>,transport:typeof fetch,parsedBody?:unknown){const req=Readable.from(parsedBody===undefined?[JSON.stringify(input)]:[]) as any;if(parsedBody!==undefined)req.body=parsedBody;req.method='POST';req.url='/api/jev-check';req.headers={host:'localhost',...headers};let status=0;let response='';const res={writeHead(n:number){status=n;},end(v:string){response+=v;}} as any;await checkJev(req,res,true,transport);return{status,body:JSON.parse(response)};}
test('Jev check uses saved prescription and one provider call; cached requests do not repeat',async()=>{const restore=await setup();let calls=0;try{const transport=(async()=>{calls++;return new Response(JSON.stringify({judge:'jev',decisions:[{field:'candidate_0',action:'fill',confidence:.8}],usage:{input_tokens:420,output_tokens:30}}));}) as typeof fetch;const a=await call({},transport);assert.equal(a.status,200);assert.equal(a.body.findings[0].status,'text_agrees');const b=await call({},transport);assert.equal(b.body.cacheHit,true);assert.equal(calls,1);}finally{restore();}});
test('read-only recovery never starts Jev and failed call halts all new calls',async()=>{const restore=await setup();let calls=0;try{const transport=(async()=>{calls++;return new Response('failed',{status:502});}) as typeof fetch;const first=await call({'x-tomorrow-jev-readonly':'true'},transport);assert.equal(first.body.status,'missing');assert.equal(calls,0);const second=await call({},transport);assert.equal(second.status,502);assert.equal(calls,1);const another=await call({},transport);assert.equal(another.body.status,'failed');assert.equal(calls,1);}finally{restore();}});

test('Vercel parsed bodies work without replaying a provider call',async()=>{const restore=await setup();let calls=0;try{const transport=(async()=>{calls++;return new Response(JSON.stringify({judge:'jev',decisions:[{field:'candidate_0',action:'review'}],usage:{input_tokens:100,output_tokens:10}}));}) as typeof fetch;const a=await call({},transport,input);assert.equal(a.status,200);assert.equal(a.body.status,'ok');const b=await call({},transport,JSON.stringify(input));assert.equal(b.body.cacheHit,true);assert.equal(calls,1);}finally{restore();}});
test('unlinked saved text requires its exact hash grant; readonly never starts a score',async()=>{const restore=await setup();let calls=0;try{const r={...linked,inputHash:'exact-granted-hash',fields:[{...linked.fields[0],value:'TDS',quote:'THS',verified:false}],sourceLines:[{quote:'THS',confidence:.4}]};const s=new FileStore();await s.finish(intakeKey(input),{status:'ok',result:r},10,0);const transport=(async(_u,opts)=>{calls++;assert.equal(JSON.parse(String(opts?.body)).text,'THS');return new Response(JSON.stringify({judge:'jev',decisions:[{field:'candidate_0',action:'review',confidence:.1}],usage:{input_tokens:40,output_tokens:0}}));}) as typeof fetch;const a=await call({},transport);assert.equal(a.body.status,'skipped');assert.equal(calls,0);process.env.UNLINKED_TEXT_CHECK_INPUT_HASH='wrong';assert.equal((await call({},transport)).body.status,'skipped');process.env.UNLINKED_TEXT_CHECK_INPUT_HASH='exact-granted-hash';assert.equal((await call({'x-tomorrow-jev-readonly':'true'},transport)).body.status,'missing');assert.equal(calls,0);const b=await call({},transport);assert.equal(b.body.status,'ok');assert.equal(b.body.findings[0].score,.1);assert.equal(calls,1);assert.equal((await call({},transport)).body.cacheHit,true);assert.equal(calls,1);}finally{delete process.env.UNLINKED_TEXT_CHECK_INPUT_HASH;restore();}});
