import{test}from'node:test';import assert from'node:assert/strict';import{reviewTextWithLev}from'../server/lev-gate.js';import type{IntakeLinked}from'../src/intake.js';
const result:IntakeLinked={schema_version:'intake.v1',summary:'fictional',category:'support',urgency:'unknown',fields:[{name:'frequency_1',value:'BD',quote:'FictionalName BD',evidence:[],verified:true},{name:'medicine_1',value:'unclear',quote:'?',evidence:[],verified:false}],missing:[],reviewReasons:[],inputHash:'mock',transcript:null,tokens:0,usd:0,cacheHit:false,useCase:'prescription'};
test('Lev sends only linked text, exposes raw score and keeps unlinked fields unchecked',async()=>{let calls=0;const output=await reviewTextWithLev(result,'mock',(async(_u,opts)=>{calls++;if(!opts?.body)return new Response('event: complete\ndata: '+JSON.stringify([{answers:{f0:{type:"noul",noul:.98}},usage:{input_tokens:80,output_tokens:0}}])+'\n\n');const b=JSON.parse(String(opts?.body)).data[0];assert.equal(b.state,'FictionalName BD\n?');assert.equal(Object.keys(b.questions).length,1);return new Response(JSON.stringify({event_id:'test-event'}));}) as typeof fetch);assert.equal(calls,2);assert.equal(output.findings[0].score,.98);assert.equal(output.findings[1].score,null);});
test('truncated Lev answers never count as text agreement',async()=>{const output=await reviewTextWithLev(result,'mock',(async(_u,opts)=>opts?.body?new Response(JSON.stringify({event_id:'test-event'})):new Response('event: complete\ndata: '+JSON.stringify([{answers:{f0:{type:'noul',noul:.99}},truncated:{f0:10},usage:{input_tokens:80,output_tokens:0}}])+'\n\n')) as typeof fetch);assert.equal(output.findings[0].score,null);assert.equal(output.findings[0].status,'needs_check');});
test('Space asleep response gets one call, never an automatic retry',async()=>{let calls=0;await assert.rejects(reviewTextWithLev(result,'mock',(async()=>{calls++;return new Response('asleep',{status:503});}) as typeof fetch),/asleep/);assert.equal(calls,1);});
test('unlinked values go to Lev against saved extracted lines, never certified as handwriting',async()=>{const r={...result,fields:[{...result.fields[0],value:'TDS',quote:'THS',verified:false}],sourceLines:[{quote:'THS',confidence:.4},{quote:'??? monitoring ?',confidence:.2}]};let calls=0;const out=await reviewTextWithLev(r,'fixture',(async(_u,init)=>{calls++;if(init?.body){const p=JSON.parse(String(init.body)).data[0];assert.equal(p.state,'THS\n??? monitoring ?');assert.match(p.questions.f0.instructions,/TDS/);return new Response(JSON.stringify({event_id:'fixture'}));}return new Response('event: complete\ndata: '+JSON.stringify([{answers:{f0:{type:'noul',noul:.1}},usage:{input_tokens:40,output_tokens:0}}])+'\n\n');}) as typeof fetch);assert.equal(calls,2);assert.equal(out.findings[0].score,.1);assert.equal(r.fields[0].verified,false);});
test('Lev never clips oversized text or sends it to the provider',async()=>{let calls=0;await assert.rejects(reviewTextWithLev({...result,sourceLines:[{quote:'x'.repeat(1601),confidence:1}]},'fixture',(async()=>{calls++;throw Error('unexpected');}) as typeof fetch),/too long/);assert.equal(calls,0);});
test('even high Lev score cannot verify absent TDS against THS',async()=>{const r={...result,fields:[{...result.fields[0],value:'TDS',verified:false}],sourceLines:[{quote:'THS',confidence:.4}]};const out=await reviewTextWithLev(r,'fixture',(async(_u,opts)=>opts?.body?new Response(JSON.stringify({event_id:'fixture'})):new Response('event: complete\ndata: '+JSON.stringify([{answers:{f0:{type:'noul',noul:.999}},usage:{input_tokens:40,output_tokens:0}}])+'\n\n')) as typeof fetch);assert.equal(out.findings[0].score,.999);assert.equal(out.findings[0].status,'needs_check');});

test('Lev diagnostics name the failing stage without leaking text or keys',async()=>{
 const mk=(stream:string)=>(async(_u:any,opts:any)=>opts?.body?new Response(JSON.stringify({event_id:'test-event'})):new Response(stream)) as typeof fetch;
 await assert.rejects(reviewTextWithLev(result,'SECRETKEY',mk('event: error\ndata: "private prompt text"\n\n')),(e:any)=>/error event/.test(e.message)&&!/private|SECRETKEY/.test(e.message));
 await assert.rejects(reviewTextWithLev(result,'SECRETKEY',mk('event: heartbeat\ndata: null\n\n')),(e:any)=>/ended without a result \(events: heartbeat\)/.test(e.message));
 const timeout=Object.assign(new Error('x'),{name:'TimeoutError'});
 await assert.rejects(reviewTextWithLev(result,'SECRETKEY',(async(_u:any,opts:any)=>{if(opts?.body)return new Response(JSON.stringify({event_id:'test-event'}));throw timeout;}) as typeof fetch),(e:any)=>/no result within 50s/.test(e.message));
 await assert.rejects(reviewTextWithLev(result,'SECRETKEY',(async()=>{throw timeout;}) as typeof fetch),(e:any)=>/not accepted within 10s/.test(e.message));
});

test('event id is saved before the wait and recovery only reads, never submits',async()=>{
 let saved='';const stream='event: complete\ndata: '+JSON.stringify([{answers:{f0:{type:'noul',noul:.9},f1:{type:'noul',noul:.9}},usage:{input_tokens:10,output_tokens:2}}])+'\n\n';
 const timeout=Object.assign(new Error('x'),{name:'TimeoutError'});
 await assert.rejects(reviewTextWithLev(result,'SECRETKEY',(async(_u:any,opts:any)=>{if(opts?.body)return new Response(JSON.stringify({event_id:'ev-1'}));throw timeout;}) as typeof fetch,true,async id=>{saved=id;}),/no result within 50s/);
 assert.equal(saved,'ev-1');
 const methods:string[]=[];
 const out=await reviewTextWithLev(result,'SECRETKEY',(async(u:any,opts:any)=>{methods.push(opts?.method??'GET');assert.match(String(u),/call\/score\/ev-1$/);return new Response(stream);}) as typeof fetch,true,undefined,'ev-1');
 assert.deepEqual(methods,['GET']);assert.ok(out.tokens===12);
});
test('MOCK: high Lev agreement cannot borrow a dose from another row',async()=>{const r={...result,fields:[{...result.fields[0],name:'dose_1',value:'10 mg',quote:'2) SYN-B 10 mg HS'}],sourceLines:[{quote:'1) SYN-A 5 mg BD',confidence:null},{quote:'2) SYN-B 10 mg HS',confidence:null}]};const out=await reviewTextWithLev(r,'fixture',(async(_u,opts)=>opts?.body?new Response(JSON.stringify({event_id:'fixture'})):new Response('event: complete\ndata: '+JSON.stringify([{answers:{f0:{type:'noul',noul:.999}},usage:{input_tokens:40,output_tokens:0}}])+'\n\n')) as typeof fetch);assert.equal(out.findings[0].score,.999);assert.equal(out.findings[0].status,'needs_check');});
