import {textCheckHold} from '../server/extraction.js';
import {test} from 'node:test';import assert from 'node:assert/strict';import {Readable} from 'node:stream';import {mkdtemp} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {checkLev} from '../server/lev-check.js';import {FileStore} from '../server/store.js';import {intakeKey} from '../server/intake.js';import type {IntakeLinked} from '../src/intake.js';
const input={text:'fictional prescription',file:null};
const linked:IntakeLinked={schema_version:'intake.v1',summary:'Fictional',category:'support',urgency:'unknown',fields:[{name:'medicine_1',value:'Samplemed',quote:'Rx Samplemed',evidence:[],verified:true}],missing:[],reviewReasons:[],inputHash:'abc',transcript:null,tokens:500,usd:0,cacheHit:false,useCase:'prescription'};
async function setup(){const dir=await mkdtemp(join(tmpdir(),'lev-check-'));const old=process.cwd();process.chdir(dir);textCheckHold.held=false;process.env.HF_LEV_TOKEN='fixture';process.env.LEV_PUBLIC_ENABLED='true';const s=new FileStore();await s.reserve(intakeKey(input),2_000_000,2);await s.finish(intakeKey(input),{status:'ok',result:linked},10,.001);return()=>{process.chdir(old);delete process.env.HF_LEV_TOKEN;delete process.env.LEV_PUBLIC_ENABLED;textCheckHold.held=true;};}
async function call(headers:Record<string,string>,transport:typeof fetch,parsedBody?:unknown){const req=Readable.from(parsedBody===undefined?[JSON.stringify(input)]:[]) as any;if(parsedBody!==undefined)req.body=parsedBody;req.method='POST';req.url='/api/lev-check';req.headers={host:'localhost',...headers};let status=0;let response='';const res={writeHead(n:number){status=n;},end(v:string){response+=v;}} as any;await checkLev(req,res,true,transport);return{status,body:JSON.parse(response)};}
test('unlinked saved text is checked every time; readonly never starts a score',async()=>{const restore=await setup();let calls=0;try{const r={...linked,inputHash:'exact-granted-hash',fields:[{...linked.fields[0],value:'TDS',quote:'THS',verified:false}],sourceLines:[{quote:'THS',confidence:.4}]};const s=new FileStore();await s.finish(intakeKey(input),{status:'ok',result:r},10,0);const transport=(async(_u,opts)=>{calls++;if(opts?.body){assert.equal(JSON.parse(String(opts.body)).data[0].state,'THS');return new Response(JSON.stringify({event_id:'fixture'}));}return new Response('event: complete\ndata: '+JSON.stringify([{answers:{f0:{type:'noul',noul:.1}},usage:{input_tokens:40,output_tokens:0}}])+'\n\n');}) as typeof fetch;assert.equal((await call({'x-tomorrow-lev-readonly':'true'},transport)).body.status,'missing');assert.equal(calls,0);const b=await call({},transport);assert.equal(b.body.status,'ok');assert.equal(b.body.findings[0].score,.1);assert.equal(calls,2);assert.equal((await call({},transport)).body.cacheHit,true);assert.equal(calls,2);}finally{delete process.env.UNLINKED_TEXT_CHECK_INPUT_HASH;restore();}});
test('lev held by default: no provider call, no score, status held',async()=>{const restore=await setup();let calls=0;try{textCheckHold.held=true;const transport=(async()=>{calls++;return new Response('{}');}) as typeof fetch;const r=await call({},transport);assert.equal(r.body.status,'held');assert.equal(r.body.findings,undefined);assert.equal(calls,0);}finally{restore();}});

test('lev one-shot record: runs only for the named hash, once, while the global hold stays on',async()=>{const restore=await setup();let calls=0;try{textCheckHold.held=true;const hash=intakeKey(input).replace(':intake.v1','');const transport=(async(_u:any,opts:any)=>{calls++;return opts?.body?new Response(JSON.stringify({event_id:'fixture'})):new Response('event: complete\ndata: '+JSON.stringify([{answers:{f0:{type:'noul',noul:.1}},usage:{input_tokens:40,output_tokens:0}}])+'\n\n');}) as typeof fetch;
 assert.equal((await call({},transport,{record:hash})).status,400);assert.equal(calls,0);
 process.env.TOMORROW_ONESHOT_RECORD=hash;assert.equal((await call({},transport,{record:'a'.repeat(64)})).status,400);assert.equal((await call({},transport,{record:hash,extra:1})).status,400);assert.equal(calls,0);
 const ok=await call({},transport,{record:hash});assert.equal(ok.body.status,'ok');assert.equal(calls,2);
 assert.equal((await call({},transport,{record:hash})).body.cacheHit,true);assert.equal(calls,2);
 assert.equal((await call({},transport)).body.cacheHit,true);
 }finally{delete process.env.TOMORROW_ONESHOT_RECORD;restore();}});

test('lev retry-once clears one failed entry for the one-shot record, never twice',async()=>{const restore=await setup();let calls=0;try{textCheckHold.held=true;const hash=intakeKey(input).replace(':intake.v1','');const bad=(async(_u:any,opts:any)=>{calls++;if(opts?.body)return new Response(JSON.stringify({event_id:'e'}));return new Response('event: error\ndata: x\n\n');}) as typeof fetch;
 const good=(async(_u:any,opts:any)=>{calls++;return opts?.body?new Response(JSON.stringify({event_id:'e'})):new Response('event: complete\ndata: '+JSON.stringify([{answers:{f0:{type:'noul',noul:.1}},usage:{input_tokens:40,output_tokens:0}}])+'\n\n');}) as typeof fetch;
 process.env.TOMORROW_ONESHOT_RECORD=hash;assert.equal((await call({},bad,{record:hash})).status,502);assert.equal(calls,2);
 assert.equal((await call({},good,{record:hash})).body.status,'failed');assert.equal(calls,2);// still blocked: no retry env
 process.env.TOMORROW_LEV_RETRY_ONCE=hash;const r=await call({},good,{record:hash});assert.equal(r.body.status,'ok');assert.equal(calls,4);
 const again=await call({},good,{record:hash});assert.equal(again.body.cacheHit,true);assert.equal(calls,4);
 }finally{delete process.env.TOMORROW_ONESHOT_RECORD;delete process.env.TOMORROW_LEV_RETRY_ONCE;restore();}});
test('lev retry-once cannot reopen a second failure',async()=>{const restore=await setup();let calls=0;try{textCheckHold.held=true;const hash=intakeKey(input).replace(':intake.v1','');const bad=(async(_u:any,opts:any)=>{calls++;if(opts?.body)return new Response(JSON.stringify({event_id:'e'}));return new Response('event: error\ndata: x\n\n');}) as typeof fetch;
 process.env.TOMORROW_ONESHOT_RECORD=hash;process.env.TOMORROW_LEV_RETRY_ONCE=hash;assert.equal((await call({},bad,{record:hash})).status,502);assert.equal(calls,2);
 assert.equal((await call({},bad,{record:hash})).status,502);assert.equal(calls,4);// the one allowed retry
 assert.equal((await call({},bad,{record:hash})).body.status,'failed');assert.equal(calls,4);
 }finally{delete process.env.TOMORROW_ONESHOT_RECORD;delete process.env.TOMORROW_LEV_RETRY_ONCE;restore();}});
