import type {IncomingMessage,ServerResponse} from 'node:http';
import {timingSafeEqual} from 'node:crypto';
import {FileStore,RedisStore,type Store} from './store';
import {extract,inputSchema} from './extraction';
export function storeFor(local=false):Store|null{if(local)return new FileStore();const url=process.env.UPSTASH_REDIS_REST_URL??process.env.KV_REST_API_URL,token=process.env.UPSTASH_REDIS_REST_TOKEN??process.env.KV_REST_API_TOKEN;return url&&token?new RedisStore(url,token):null;}
function enabled(local:boolean){return !!process.env.INTERFAZE_API_KEY&&process.env.FREE_CREDIT_CONFIRMED==='true'&&!!storeFor(local)&&(local||!!process.env.HOUSEHOLD_ACCESS_CODE)&&Number(process.env.TOKEN_CAP)>=1032000&&Number(process.env.CREDIT_CAP_USD)>=1.612;}
function authorized(req:IncomingMessage,local:boolean){if(local)return true;const actual=Buffer.from(req.headers.authorization?.replace(/^Bearer /,'')??''),expected=Buffer.from(process.env.HOUSEHOLD_ACCESS_CODE??'');return expected.length>=16&&actual.length===expected.length&&timingSafeEqual(actual,expected);}
export async function handle(req:IncomingMessage,res:ServerResponse,local=false){const reply=(status:number,body:unknown)=>{res.writeHead(status,{'Content-Type':'application/json','Cache-Control':'no-store'});res.end(JSON.stringify(body));};
 if(req.url?.split('?')[0]==='/api/status'){const setup=enabled(local);const budget=authorized(req,local)&&storeFor(local)?await storeFor(local)!.ledger().catch(()=>null):null;reply(200,{enabled:setup,requiresAccessCode:!local,budget,message:setup?'Interfaze is connected.':'Extraction setup pending. You can save notices and add your own reminders.'});return;}
 if(req.method!=='POST'){reply(405,{error:'Method not allowed'});return;}
 const origin=req.headers.origin;if(origin){try{if(new URL(origin).host!==req.headers.host){reply(403,{error:'Origin rejected'});return;}}catch{reply(403,{error:'Invalid origin'});return;}}
 if(!enabled(local)){reply(503,{error:'SETUP_REQUIRED: the owner has not enabled Interfaze with a free-credit budget and persistent cache. Notice saved locally.'});return;}
 if(!authorized(req,local)){reply(401,{error:'Enter your household access code in Settings.'});return;}
 try{let length=0;const chunks:Buffer[]=[];for await(const chunk of req){const b=Buffer.from(chunk);length+=b.length;if(length>4_200_000){reply(413,{error:'File too large. Use a file below 3 MB.'});return;}chunks.push(b);}const parsedBody=(req as IncomingMessage & {body?:unknown}).body;const body=parsedBody===undefined?JSON.parse(Buffer.concat(chunks).toString()):typeof parsedBody==='string'?JSON.parse(parsedBody):parsedBody;if(Buffer.byteLength(JSON.stringify(body))>4_200_000){reply(413,{error:'File too large. Use a file below 3 MB.'});return;}const input=inputSchema.parse(body);const result=await extract(input,storeFor(local)!,{key:process.env.INTERFAZE_API_KEY!,freeConfirmed:true,tokenCap:Number(process.env.TOKEN_CAP),creditCap:Number(process.env.CREDIT_CAP_USD)});reply(200,result);}catch(e){const message=e instanceof Error?e.message:'Extraction failed';reply(400,{error:message.includes('Authorization')?'Extraction failed':message.slice(0,800)});}
}
