/** Separate, shared Lev usage ledger. Reservations are serialized across instances.
 * A pending/uncertain request halts all further Lev calls; no automatic retry.
 */
import {mkdir,open,readFile,rename,unlink,writeFile} from 'node:fs/promises';
import type {GateFinding} from './jev-gate.js';
export type LevEntry={status:'pending'|'ok'|'failed';findings?:GateFinding[];error?:string};
export type LevLedger={tokens:number;halted:boolean;reason?:string};
export interface LevBudget{lookup(id:string):Promise<LevEntry|null>;reserve(id:string):Promise<void>;finish(id:string,findings:GateFinding[],tokens:number):Promise<void>;retryOnce(id:string,nonce?:string):Promise<boolean>;noteEvent(id:string,eventId:string):Promise<void>;eventFor(id:string):Promise<string|null>;recover(id:string,findings:GateFinding[],tokens:number):Promise<boolean>;fail(id:string,error:string):Promise<void>;ledger():Promise<LevLedger>}
export const CAP=200_000, RESERVE=100_000;
const blank=():LevLedger=>({tokens:0,halted:false});
export class FileLevBudget implements LevBudget{
 constructor(private dir='.private'){}
 private async read(){await mkdir(this.dir,{recursive:true,mode:0o700});try{return JSON.parse(await readFile(this.dir+'/lev-state.json','utf8')) as {ledger:LevLedger;entries:Record<string,LevEntry>};}catch(e){if((e as NodeJS.ErrnoException).code!=='ENOENT')throw e;return{ledger:blank(),entries:{}};}}
 private async change(fn:(s:{ledger:LevLedger;entries:Record<string,LevEntry>})=>void){await mkdir(this.dir,{recursive:true,mode:0o700});const lock=await open(this.dir+'/lev.lock','wx').catch(()=>{throw Error('LEV_BUSY: no provider call.');});try{const s=await this.read();fn(s);await writeFile(this.dir+'/lev.tmp',JSON.stringify(s),{mode:0o600});await rename(this.dir+'/lev.tmp',this.dir+'/lev-state.json');}finally{await lock.close();await unlink(this.dir+'/lev.lock');}}
 async lookup(id:string){return(await this.read()).entries[id]??null;}
 async ledger(){return(await this.read()).ledger;}
 async reserve(id:string){await this.change(s=>{if(s.entries[id])throw Error('LEV_ALREADY_RESERVED: no repeat.');if(s.ledger.halted)throw Error('LEV_HALTED: usage uncertain.');if(s.ledger.tokens+RESERVE>CAP)throw Error('LEV_CAP_REACHED: no provider call.');s.entries[id]={status:'pending'};s.ledger.halted=true;s.ledger.reason='Call pending';});}
 async finish(id:string,findings:GateFinding[],tokens:number){await this.change(s=>{if(s.entries[id]?.status!=='pending')throw Error('LEV_ENTRY_NOT_PENDING');s.entries[id]={status:'ok',findings};s.ledger={tokens:s.ledger.tokens+tokens,halted:!Number.isSafeInteger(tokens)||tokens<0||tokens>RESERVE||s.ledger.tokens+tokens>CAP};if(s.ledger.halted)s.ledger.reason='Usage exceeded reservation; no further calls';});}
 async retryOnce(id:string,nonce=''){const slot=id+(nonce?':'+nonce:'');let done=false;await this.change(s=>{const m=s as unknown as {retried?:Record<string,boolean>};m.retried??={};if(s.entries[id]?.status==='failed'&&!m.retried[slot]){m.retried[slot]=true;delete s.entries[id];s.ledger.halted=false;delete s.ledger.reason;done=true;}});return done;}
 async noteEvent(id:string,eventId:string){await this.change(s=>{const m=s as unknown as {events?:Record<string,string>};m.events??={};m.events[id]=eventId;});}
 async eventFor(id:string){return((await this.read()) as unknown as {events?:Record<string,string>}).events?.[id]??null;}
 /** Turns one timed-out entry into its finished result. Needs a saved event id; usage is added to the ledger once. */
 async recover(id:string,findings:GateFinding[],tokens:number){let done=false;await this.change(s=>{const m=s as unknown as {events?:Record<string,string>};if(s.entries[id]?.status!=='failed'||!m.events?.[id]||!Number.isSafeInteger(tokens)||tokens<0)return;s.entries[id]={status:'ok',findings};const total=s.ledger.tokens+tokens;s.ledger={tokens:total,halted:tokens>RESERVE||total>CAP};if(s.ledger.halted)s.ledger.reason='Usage exceeded reservation; no further calls';done=true;});return done;}
 async fail(id:string,error:string){await this.change(s=>{s.entries[id]={status:'failed',error};s.ledger.halted=true;s.ledger.reason=error;});}
}
export class RedisLevBudget implements LevBudget{
 constructor(private url:string,private token:string){}
 private async command(...args:unknown[]){const r=await fetch(this.url,{method:'POST',headers:{Authorization:`Bearer ${this.token}`,'Content-Type':'application/json'},body:JSON.stringify(args),signal:AbortSignal.timeout(10000)});if(!r.ok)throw Error('LEV_CACHE_UNAVAILABLE: no provider call.');const j=await r.json() as {result:unknown;error?:string};if(j.error)throw Error('LEV_CACHE_ERROR: '+j.error);return j.result;}
 async lookup(id:string){const v=await this.command('GET','tomorrow:lev:entry:'+id);return v?JSON.parse(String(v)) as LevEntry:null;}
 async ledger(){const v=await this.command('GET','tomorrow:lev:ledger');return v?JSON.parse(String(v)) as LevLedger:blank();}
 async reserve(id:string){const script=`if redis.call('EXISTS',KEYS[1])==1 then return 'ALREADY_RESERVED' end;local v=redis.call('GET',KEYS[2]);local s=v and cjson.decode(v) or {tokens=0,halted=false};if s.halted then return 'HALTED' end;if tonumber(s.tokens)+100000>200000 then return 'CAP_REACHED' end;redis.call('SET',KEYS[1],'{"status":"pending"}');s.halted=true;s.reason='Call pending';redis.call('SET',KEYS[2],cjson.encode(s));return 'OK'`;
 const r=await this.command('EVAL',script,2,'tomorrow:lev:entry:'+id,'tomorrow:lev:ledger');if(r!=='OK')throw Error('LEV_'+r+': no provider call.');}
 async finish(id:string,findings:GateFinding[],tokens:number){if(!Number.isSafeInteger(tokens)||tokens<0)throw Error('LEV_INVALID_USAGE');const script=`local s=cjson.decode(redis.call('GET',KEYS[2]));if redis.call('GET',KEYS[1])~='{"status":"pending"}' then return 'NOT_PENDING' end;s.tokens=s.tokens+tonumber(ARGV[2]);s.halted=tonumber(ARGV[2])>100000 or s.tokens>200000;if s.halted then s.reason='Usage exceeded reservation; no further calls' else s.reason=nil end;redis.call('SET',KEYS[1],ARGV[1]);redis.call('SET',KEYS[2],cjson.encode(s));return 'OK'`;const r=await this.command('EVAL',script,2,'tomorrow:lev:entry:'+id,'tomorrow:lev:ledger',JSON.stringify({status:'ok',findings}),tokens);if(r!=='OK')throw Error('LEV_'+r);}
 /** One-time recovery of a failed entry: needs a never-used marker, so a second failure cannot reopen it. */
 async retryOnce(id:string,nonce=''){const script=`local e=redis.call('GET',KEYS[1]);if not e or cjson.decode(e).status~='failed' then return 'NOT_FAILED' end;if redis.call('EXISTS',KEYS[3])==1 then return 'ALREADY_RETRIED' end;redis.call('SET',KEYS[3],'1');redis.call('DEL',KEYS[1]);local l=cjson.decode(redis.call('GET',KEYS[2]));l.halted=false;l.reason=nil;redis.call('SET',KEYS[2],cjson.encode(l));return 'OK'`;return await this.command('EVAL',script,3,'tomorrow:lev:entry:'+id,'tomorrow:lev:ledger','tomorrow:lev:retried:'+id+(nonce?':'+nonce:''))==='OK';}
 async noteEvent(id:string,eventId:string){await this.command('SET','tomorrow:lev:event:'+id,eventId);}
 async eventFor(id:string){const v=await this.command('GET','tomorrow:lev:event:'+id);return v?String(v):null;}
 async recover(id:string,findings:GateFinding[],tokens:number){if(!Number.isSafeInteger(tokens)||tokens<0)return false;const script=`local e=redis.call('GET',KEYS[1]);if not e or cjson.decode(e).status~='failed' or redis.call('EXISTS',KEYS[3])==0 then return 'NO' end;local s=cjson.decode(redis.call('GET',KEYS[2]));s.tokens=s.tokens+tonumber(ARGV[2]);s.halted=tonumber(ARGV[2])>100000 or s.tokens>200000;if s.halted then s.reason='Usage exceeded reservation; no further calls' else s.reason=nil end;redis.call('SET',KEYS[1],ARGV[1]);redis.call('SET',KEYS[2],cjson.encode(s));return 'OK'`;return await this.command('EVAL',script,3,'tomorrow:lev:entry:'+id,'tomorrow:lev:ledger','tomorrow:lev:event:'+id,JSON.stringify({status:'ok',findings}),tokens)==='OK';}
 async fail(id:string,error:string){await this.command('EVAL',`local s=cjson.decode(redis.call('GET',KEYS[2]));s.halted=true;s.reason=ARGV[2];redis.call('SET',KEYS[1],ARGV[1]);redis.call('SET',KEYS[2],cjson.encode(s));return 'OK'`,2,'tomorrow:lev:entry:'+id,'tomorrow:lev:ledger',JSON.stringify({status:'failed',error}),error);}
}
