import {mkdir,readFile,writeFile,rename,open,unlink} from 'node:fs/promises';
export type Ledger={tokens:number;usd:number;halted:boolean;reason?:string;lastCall:number};
export type Entry={status:'pending'|'ok'|'failed';result?:unknown;error?:string;raw?:unknown};
export interface Store{lookup(key:string):Promise<Entry|null>;reserve(key:string,tokenCap:number,creditCap:number,deviceId?:string):Promise<void>;finish(key:string,entry:Entry,tokens:number,usd:number):Promise<void>;fail(key:string,error:string,raw?:unknown):Promise<void>;ledger():Promise<Ledger>}
export const RESERVE_TOKENS=1_032_000,RESERVE_USD=1.612;
const empty=():Ledger=>({tokens:0,usd:0,halted:false,lastCall:0});
export class FileStore implements Store{
 constructor(private dir='.private'){}
 private async state(){await mkdir(this.dir,{recursive:true,mode:0o700});try{return JSON.parse(await readFile(this.dir+'/state.json','utf8')) as {ledger:Ledger;entries:Record<string,Entry>};}catch(e){if((e as NodeJS.ErrnoException).code!=='ENOENT')throw e;return{ledger:empty(),entries:{}};}}
 private async mutate(fn:(s:{ledger:Ledger;entries:Record<string,Entry>})=>void){await mkdir(this.dir,{recursive:true});const lock=await open(this.dir+'/state.lock','wx').catch(()=>{throw Error('BUSY: another operation is in progress.');});try{const s=await this.state();fn(s);await writeFile(this.dir+'/state.tmp',JSON.stringify(s),{mode:0o600});await rename(this.dir+'/state.tmp',this.dir+'/state.json');}finally{await lock.close();await unlink(this.dir+'/state.lock');}}
 async lookup(key:string):Promise<Entry|null>{return(await this.state()).entries[key]??null;}
 async ledger(){return(await this.state()).ledger;}
 async reserve(key:string,tokenCap:number,creditCap:number,deviceId=''){await this.mutate(s=>{if(s.entries[key])throw Error('ALREADY_RESERVED: this input will not be called again.');if(s.ledger.halted)throw Error('HALTED: an earlier call failed or has uncertain usage.');if(s.ledger.tokens+RESERVE_TOKENS>tokenCap||s.ledger.usd+RESERVE_USD>creditCap)throw Error('CAP_REACHED: not enough free budget for a conservative reservation.');if(Date.now()-s.ledger.lastCall<1000)throw Error('RATE_LIMIT: wait a moment.');if(deviceId){const limits=(s as typeof s & {deviceLimits?:Record<string,{window:number;count:number}>}).deviceLimits??={};const now=Date.now(),v=limits[deviceId];if(v&&now-v.window<3600000&&v.count>=6)throw Error('DEVICE_RATE_LIMIT: up to six new extractions per device per hour. No API call made.');limits[deviceId]=v&&now-v.window<3600000?{window:v.window,count:v.count+1}:{window:now,count:1};(s as typeof s & {deviceLimits?:typeof limits}).deviceLimits=limits;}s.entries[key]={status:'pending'};s.ledger.halted=true;s.ledger.reason='Call pending; automatic retry prohibited';s.ledger.lastCall=Date.now();});}
 async finish(key:string,entry:Entry,tokens:number,usd:number){await this.mutate(s=>{s.entries[key]=entry;s.ledger={tokens:s.ledger.tokens+tokens,usd:s.ledger.usd+usd,halted:tokens>RESERVE_TOKENS||usd>RESERVE_USD,lastCall:s.ledger.lastCall};});}
 async fail(key:string,error:string,raw?:unknown){await this.mutate(s=>{s.entries[key]={status:'failed',error,raw};s.ledger.halted=true;s.ledger.reason=error;});}
}
// Redis executes reservations atomically across all serverless instances. No TTL:
// an uncertain call cannot silently become eligible for a repeat request.
export class RedisStore implements Store{
 constructor(private url:string,private token:string){}
 private async command(...args:unknown[]){const r=await fetch(this.url,{method:'POST',headers:{Authorization:`Bearer ${this.token}`,'Content-Type':'application/json'},body:JSON.stringify(args),signal:AbortSignal.timeout(10000)});if(!r.ok)throw Error('CACHE_UNAVAILABLE: no API call made.');const data=await r.json() as {result:unknown;error?:string};if(data.error)throw Error('CACHE_ERROR: '+data.error);return data.result;}
 async lookup(key:string):Promise<Entry|null>{const s=await this.command('GET','tomorrow:input:'+key);return s?JSON.parse(String(s)) as Entry:null;}
 async ledger(){const s=await this.command('GET','tomorrow:ledger');return s?JSON.parse(String(s)) as Ledger:empty();}
 async reserve(key:string,tokenCap:number,creditCap:number,deviceId=''){const script=`local e=redis.call('GET',KEYS[1]); if e then return 'ALREADY_RESERVED' end; local l=redis.call('GET',KEYS[2]); local s=l and cjson.decode(l) or {tokens=0,usd=0,halted=false,lastCall=0}; if s.halted then return 'HALTED' end; if s.tokens+1032000>tonumber(ARGV[1]) or s.usd+1.612>tonumber(ARGV[2]) then return 'CAP_REACHED' end; if tonumber(ARGV[3])-s.lastCall<1000 then return 'RATE_LIMIT' end; if ARGV[4]~='' then local count=tonumber(redis.call('GET',KEYS[3]) or '0');if count>=6 then return 'DEVICE_RATE_LIMIT' end;redis.call('INCR',KEYS[3]);if count==0 then redis.call('EXPIRE',KEYS[3],3600) end end; s.halted=true;s.lastCall=tonumber(ARGV[3]);s.reason='Call pending';redis.call('SET',KEYS[1],'{"status":"pending"}');redis.call('SET',KEYS[2],cjson.encode(s));return 'OK'`;
 const r=await this.command('EVAL',script,3,'tomorrow:input:'+key,'tomorrow:ledger','tomorrow:device:'+deviceId,tokenCap,creditCap,Date.now(),deviceId);if(r!=='OK')throw Error(String(r)+': no additional API call made.');}
 async finish(key:string,entry:Entry,tokens:number,usd:number){await this.command('EVAL',`local s=cjson.decode(redis.call('GET',KEYS[2]));s.tokens=s.tokens+tonumber(ARGV[2]);s.usd=s.usd+tonumber(ARGV[3]);s.halted=tonumber(ARGV[2])>1032000 or tonumber(ARGV[3])>1.612;s.reason=nil;redis.call('SET',KEYS[1],ARGV[1]);redis.call('SET',KEYS[2],cjson.encode(s));return 'OK'`,2,'tomorrow:input:'+key,'tomorrow:ledger',JSON.stringify(entry),tokens,usd);}
 async fail(key:string,error:string,raw?:unknown){await this.command('SET','tomorrow:input:'+key,JSON.stringify({status:'failed',error,raw}));/* reservation already halted ledger */}
}
